apiVersion: v1
kind: Pod
metadata:
  name: oracledb
  labels:
    app.kubernetes.io/name: oracledb
spec:
  containers:
  - name: oracledb
    image: gvenzl/oracle-free:23
    ports:
    - containerPort: 1521
    env:
      - name: APP_USER
        value: usah
      - name: APP_USER_PASSWORD
        value: pass
      - name: ORACLE_RANDOM_PASSWORD
        value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: oracledb
spec:
  selector:
    app.kubernetes.io/name: oracledb
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521
---
apiVersion: v1
kind: Secret
metadata:
  name: dbt-secret
stringData:
  DBT_ENV_SECRET_PASS: pass
